name: Deploy to Firebase

on: 
  push:
    paths:
      - 'storage.rules'
      - 'firestore.rules'

jobs:
  deploy:
    name: Deploy firesore and storage rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: w9jds/firebase-action@master
        with: 
        args: deploy --only firestore:rules storage:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
